contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #flupipe channel"
    url: https://nfcore.slack.com/channels/flupipe
    about: Discussion about the nf-core/flupipe pipeline
